name: Version Tag Deployment

on:
  workflow_dispatch:
    inputs:
      extension:
        type: choice
        options:
          - "firestore-chatgpt-bot"
        required: true
        description: "Extension Name"
      version:
        type: string
        required: true
        description: "Extension Version"
      commit:
        type: string
        required: false
        description: "Commit ID to be deployed (Defaults to HEAD)"

env:
  TARGET: ${{ github.event.inputs.extension }}
  VERSION_NUMBER: ${{ github.event.inputs.version }}
  TAG_NAME: ${{ github.event.inputs.extension }}/v${{ github.event.inputs.version }}

jobs:
  push-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.commit }}

      - name: Push tag
        run: |
          git tag ${{ env.TAG_NAME }}
          git push origin ${{ env.TAG_NAME }}